version: '3.0'

services:
  frontend-app:
    build:
      context: . # 当前目录
      dockerfile: Dockerfile

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./dist:/usr/share/nginx/html # 映射构建输出到 Nginx
