version: '3.0'

services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./dist:/usr/share/nginx/html # 映射前端构建输出到 Nginx

  frontend-app:
    build:
      context: .
      dockerfile: Dockerfile
